### ISSUE TITLE
Kyber market srcQty amount must reflect precision of the src token

### ISSUE THREAD

**Issue by chatch** [0xFutures/protocol#11]
We've been assuming a precision of 18 on all tokens so far.

However market tokens we intend on using have different precision of 6 (USDC) and 8 (WBTC) respectively.

Ensure all srcQty amounts in the trade and getExpectedRate calls are calculated using the decimals amount on the src ERC20 contract.

**Comment by julien-rg** [comment]
I added a new optional field for the markets in the config file:  decimals
